module.exports = {
  AZUREAD_TOKEN_CONFIG: {
    jwksUri: process.env.AZUREAD_JWK_URI,
    issuer: process.env.AZUREAD_ISSUER_URI,
    audience: process.env.AZUREAD_CLIENTID
    },
    AZUREAD_ALLOWEDGROUPS: process.env.AZUREAD_ALLOWEDGROUPS,
    APIKEYS: process.env.APIKEYS,
    APIKEYS_MINIMUM_LENGTH: process.env.APIKEYS_MINIMUM_LENGTH || 24,
    AZURE_BLOB_CONNECTIONSTRING: process.env.AZURE_BLOB_CONNECTIONSTRING,
    AZURE_BLOB_CONTAINERNAME: process.env.AZURE_BLOB_CONTAINERNAME,
    BYPASS_REGISTRATION_THRESHOLD: process.env.BYPASS_REGISTRATION_THRESHOLD,
    VTFK_MATRIKKELPROXY_BASEURL: process.env.VTFK_MATRIKKELPROXY_BASEURL,
    VTFK_MATRIKKELPROXY_APIKEY: process.env.VTFK_MATRIKKELPROXY_APIKEY,
    VTFK_PDFGENERATOR_ENDPOINT: process.env.VTFK_PDFGENERATOR_ENDPOINT,
    VTFK_P360_ARCHIVE_ENDPOINT: process.env.VTFK_P360_ARCHIVE_ENDPOINT,
    VTFK_P360_ARCHIVE_SUBSCRIPTION_KEY: process.env.VTFK_P360_ARCHIVE_SUBSCRIPTION_KEY
}